#!/bin/sh

LAZABS=../../eld

TESTS="flat-loops.smt2 booleans.smt2 chc-LIA-Lin_421.smt2"

for name in $TESTS; do
    echo
    echo $name
    $LAZABS -pngNo -ssol -abstract:off -stac -cex "$@" $name 2>&1 | grep -v "^Elapsed Time"
done

