#!/bin/sh

LAZABS=../../eld

TESTS="inconclusive.smt2 \
       loop.smt2 \
       loop2.smt2 \
       mccarthy91_bv8.smt2 \
       mccarthy91_bv32.smt2 \
       multiplication.smt2 \
       nonlinear.smt2 \
       quantifier.smt2 \
       substring.error.nts.smt2 \
       conjunctElimBug.smt2 \
       sign-extend.smt2 \
       bv2intnat.smt2 \
       bv2intnat2.smt2 \
       bitwise6.smt2 \
       test0.correct.pierre_bv8.smt2 \
       test0.correct.pierre_bv32.smt2"

for name in $TESTS; do
    echo
    echo $name
    $LAZABS -cex -abstract:off "$@" $name 2>&1 | grep -v 'at '
done

TESTS="int2bv.smt2"

for name in $TESTS; do
    echo
    echo $name
    $LAZABS "$@" $name 2>&1 | grep -v 'at '
done

