#!/bin/sh

dotfilebase="/tmp/.lazabs"

me=`whoami`
portfile="$dotfilebase"_"$me"

lockfile="$dotfilebase"_lock_"$me"

if [ $(uname) = "Linux" ]; then
    pathCmd="readlink -f"
elif [ $(uname) = "Darwin" ]; then
    pathCmd="stat -f %N"
else
    pathCmd="realpath"
fi

cleanup() {
    rm -f "$lockfile"
    # leave $portfile in place as it might contain server output
    exit 1
}

trap 'cleanup' ERR


################################################################################

startDaemon() {
    trap 'cleanup' ERR

    while [ -f "$lockfile" ] && \
          [ $(( `date +%s` - `date -r "$lockfile" +%s` )) -le 10 ]; do
        # apparently a concurrent script is starting up the daemon
        # already
        echo "waiting ..."
        sleep 1
    done

    if [ ! -f "$portfile" ]; then
        touch "$lockfile"

        BASEDIR=`dirname $($pathCmd $0)`
        . $BASEDIR/eldEnv

        tempportfile=`mktemp`
        touch "$tempportfile"
        chmod go-rwx "$tempportfile"

        $LAZABS_CMD lazabs.ServerMain >"$tempportfile" &

        sleep 1
        while [ `wc -l "$tempportfile" | gawk '{ printf $1 }'` -lt 2 ]; do
            sleep 1
        done

        mv "$tempportfile" "$portfile"
        rm "$lockfile"
    fi
}

################################################################################

if [ ! -f "$portfile" ]; then
    startDaemon
fi
port=`head -n1 "$portfile"`
if ! nc -z localhost $port; then
    echo "Cannot connect to server. Server could not be started or dead port file at $portfile"
    exit 2
fi

mainProcess=$$

success=1
until [ $success -eq 0 ]; do

    (
        # send the ticket
        tail -n1 "$portfile"

        # command line arguments
        for var; do
	    case "$var" in
		-hints:*)
		    echo -hints:`$pathCmd "${var#-hints:}"`
		    ;;
		-*|+*)
		    echo "$var"
		    ;;
		*)
		    echo `$pathCmd "$var"`
		    ;;
	    esac
        done

        echo "PROVE_AND_EXIT"

        # ping the daemon every second, to show that we are still
        # alive
        {
            sleep 1
            while ps -p $mainProcess >/dev/null; do
                echo "PING"
                sleep 1
            done
        } &
    ) | nc localhost $port |
    (
        # grep will raise an error here if server output starts with "ERROR"
        read server_reply;
        echo "$server_reply";
        echo "$server_reply" | grep -q -v "^ERROR:"
    )

    success=$?

    if [ $success -ne 0 ]; then
        rm "$portfile"
        startDaemon
    fi

done
