#!/bin/sh

LAZABS=../../eld

TESTS="test1.hcc test2.hcc test2b.hcc test2c.hcc test3.hcc test4.hcc test5.hcc \
       test-para1.hcc test-para2.hcc lazy-eval1.hcc \
       jumps.hcc jumps2.hcc jumps3.hcc \
       functions.hcc functions2.hcc extended-decl.hcc inits.hcc \
       shadowing.hcc disconnected-assertions.hcc \
       atomic1.hcc atomic2.hcc atomic3.hcc atomic3b.hcc \
       clocks1.hcc clocks2.hcc"

for name in $TESTS; do
    echo
    echo $name
    $LAZABS -cex "$@" $name
done

TESTS="test6.hcc test7.hcc loop1.hcc loop2.hcc locking.hcc"

for name in $TESTS; do
    echo
    echo $name
    $LAZABS -cex -abstract "$@" $name
done
