#!/bin/sh

LAZABS=../../eld

TESTS="test1.hcc test2.hcc test2b.hcc test2c.hcc test3.hcc test4.hcc test5.hcc \
       test-para1.hcc test-para2.hcc lazy-eval1.hcc \
       jumps.hcc jumps2.hcc jumps3.hcc \
       functions.hcc functions2.hcc extended-decl.hcc \
       inits.hcc inits2.hcc inits3.hcc \
       shadowing.hcc disconnected-assertions.hcc \
       atomic1.hcc atomic2.hcc atomic3.hcc atomic3b.hcc atomic3c.hcc \
       atomic3d.hcc atomic3e.hcc atomic3f.hcc atomic4.hcc \
       clocks1.hcc clocks2.hcc clocks3.hcc clocks4.hcc clocks5.hcc \
       fischer.hcc diamond_true-unreach-call1.c unsigned1.hcc \
       literals.c predicates.hcc"

for name in $TESTS; do
    echo
    echo $name
    $LAZABS -cex "$@" $name 2>&1 | grep -v 'at '
done

TESTS="test6.hcc test7.hcc loop1.hcc loop2.hcc locking.hcc"

for name in $TESTS; do
    echo
    echo $name
    $LAZABS -cex -abstract "$@" $name
done
