#!/bin/sh

LAZABS=../../eld

TESTS="mccarthy91.nts.smt2 \
       mccarthy92.nts.smt2 \
       palindrome.nts.smt2 \
       amotsa.smt2 \
       substring.error.nts.smt2 \
       test0.correct.pierre.nts.smt2 \
       rate_limiter.c.nts.smt2 \
       a_1.source.smt2 \
       uninterpreted_fun.smt2 \
       inconclusive.smt2 \
       quantifier.smt2 \
       nonlinear.smt2 \
       nonlinear2.smt2 \
       multiple-pos.smt2 \
       slicing-bug.smt2 \
       clause-shortener-bug.smt2 \
       extract.smt2 \
       solution-verifier-bug.smt2 \
       groebner-bug.smt2"

for name in $TESTS; do
    echo
    echo $name
    $LAZABS -pngNo -ssol -abstract:off "$@" $name 2>&1 | grep -v "^Elapsed Time"
done

