#!/bin/sh

set -e

./rundir horn-hcc "" -assert -t:60
./rundir horn-hcc-2 "" -assert -t:60
./rundir horn-quantifiers "" -assert -t:90
./rundir horn-prolog "" -assert -t:60
./rundir horn-smt-lib "" -assert -t:60
./rundir horn-abstract "" -assert -t:60 -abstractTO:4
./rundir horn-arrays ""

# ./rundir horn-concurrency ""
