#!/bin/bash

set -e

DIR="$1"
shift

ANSWER_SUFFIX="$1"
shift

[ -d "$DIR" ] || exit 1

echo -n "$DIR ($@) ... "

export TIMEFORMAT="%U"
TIME=`time ( cd $DIR; ./runtests "$@" >Output"$ANSWER_SUFFIX" 2>&1; ) 2>&1`

res=0

if cmp -s "$DIR"/Answers"$ANSWER_SUFFIX" "$DIR"/Output"$ANSWER_SUFFIX"; then
    tput setaf 2
    echo -ne "\tSucceeded"
    tput sgr0
else
    tput setaf 1
    echo -e "\tFAILED"
    tput sgr0
    echo
    diff "$DIR"/Answers"$ANSWER_SUFFIX" "$DIR"/Output"$ANSWER_SUFFIX" || true
    echo
    cp "$DIR"/Output"$ANSWER_SUFFIX" "$DIR"/Output"$ANSWER_SUFFIX"-"`date`"
    res=1
fi

echo -n " ($TIME"
echo "s)"

exit $res
