#!/bin/sh

LAZABS=../../eld

TESTS="converging.smt2 \
       converging-unsat.smt2"

for name in $TESTS; do
    echo
    echo $name
    $LAZABS -pngNo -abstract:off "$@" $name 2>&1 | grep -v "^Elapsed Time"
done

