#!/bin/sh

LAZABS=../../eld

TESTS="converging.smt2 \
       converging-unsat.smt2 \
       preproc-exception.smt2 \
       divzero.smt2"

for name in $TESTS; do
    echo
    echo $name
    $LAZABS -pngNo -abstract:off "$@" $name 2>&1 | grep -v "^Elapsed Time"
done

echo
echo monniaux-loop3.smt2
$LAZABS -abstract:relEqs2 -pngNo "$@" monniaux-loop3.smt2 2>&1 | grep -v "^Elapsed Time"
