#!/bin/sh

LAZABS=../../eld

TESTS="atomic3e.hcc atomic3f.hcc \
       clocks1.hcc clocks2.hcc clocks3.hcc clocks4.hcc clocks5.hcc \
       fischer.hcc lazy-and-or-bug.hcc \
       channels.hcc channels-2.hcc channels-2b.hcc channels-3.hcc \
       duration1.hcc duration2.hcc \
       duration3.hcc duration3b.hcc duration3c.hcc duration3d.hcc \
       nonlinear1.hcc nonlinear2.hcc typedef1.hcc switch1.hcc switch2.hcc"

for name in $TESTS; do
    echo
    echo $name
    $LAZABS -cex -abstract:off "$@" $name 2>&1 | grep -v 'at '
done

TESTS="hints.hcc hints2.hcc hints3.hcc"

for opt in -abstract -abstract:manual; do
for name in $TESTS; do
    echo
    echo $name
    $LAZABS -cex $opt "$@" $name
done
done

TESTS="interval-propagator-bug.hcc"

for name in $TESTS; do
    echo
    echo $name
    $LAZABS -cex -abstract "$@" $name
done

echo
echo hints4.hcc
$LAZABS -statistics -abstract:off "$@" hints4.hcc 2>&1 | grep 'SAFE\|CEGAR iterations'
