#!/bin/sh

LAZABS=../../eld

TESTS="atomic3e.hcc atomic3f.hcc \
       clocks1.hcc clocks2.hcc clocks3.hcc clocks4.hcc clocks5.hcc \
       fischer.hcc lazy-and-or-bug.hcc"

for name in $TESTS; do
    echo
    echo $name
    $LAZABS -cex -abstract:off "$@" $name 2>&1 | grep -v 'at '
done

TESTS="hints.hcc hints2.hcc hints3.hcc"

for opt in -abstract -abstract:manual; do
for name in $TESTS; do
    echo
    echo $name
    $LAZABS -cex $opt "$@" $name
done
done

echo
echo hints4.hcc
$LAZABS -log -abstract:off "$@" hints4.hcc | grep 'SAFE\|CEGAR iterations'
