#!/bin/sh

LAZABS=../../eld

TESTS="merge.horn \
       gcd.horn \
       mult.horn \
       Levenstein.horn \
       disjunctive.horn \
       mccarthy91.nts.horn \
       mccarthy92.nts.horn \
       palindrome.nts.horn \
       listcounter.error.nts.horn \
       long-body.horn \
       long-body2.horn"

for name in $TESTS; do
    echo
    echo $name
    $LAZABS -pngNo -sol -cex -abstract:off "$@" $name 2>&1 | grep -v "^Elapsed Time"
done

$LAZABS -pngNo -abstract:off -sol -log "$@" zero-iterations.horn -hints:zero-iterations.preds 2>&1 | grep -iv "time"

echo $name
$LAZABS -pngNo -sol -cex -splitClauses -abstract:off "$@" long-body2.horn 2>&1 | grep -v "^Elapsed Time"
