#!/bin/sh

LAZABS=../../eld

TESTS="merge.horn \
       gcd.horn \
       Levenstein.horn \
       disjunctive.horn \
       mccarthy91.nts.horn \
       mccarthy92.nts.horn \
       palindrome.nts.horn \
       listcounter.error.nts.horn \
       long-body.horn \
       long-body2.horn \
       nullary-bug.horn"

for name in $TESTS; do
    echo
    echo $name
    $LAZABS -pngNo -sol -cex -abstract:off "$@" $name 2>&1 | grep -v "^Elapsed Time"
done

echo mult.horn
$LAZABS -pngNo -cex -abstract:relIneqs -abstractTO:4 "$@" mult.horn 2>&1 | grep -v "^Elapsed Time"

echo nullary-bug.horn
$LAZABS -pngNo -sol -cex -abstract "$@" nullary-bug.horn 2>&1 | grep -v "^Elapsed Time"

echo zero-iterations.horn
$LAZABS -pngNo -abstract:off -sol -log "$@" zero-iterations.horn -hints:zero-iterations.preds 2>&1 | grep -iv 'time\|[0-9]ms'

echo long-body2.horn
$LAZABS -pngNo -sol -cex -splitClauses:2 -abstract:off "$@" long-body2.horn 2>&1 | grep -v "^Elapsed Time"
