#!/bin/sh

export LAZABS_HOME=../..
export JAR="${LAZABS_HOME}"/target/scala-*/Eldarica-assembly-*.jar
export JAVA_OPTS="-Xmx2024m -Xss20000k -cp $JAR"

for mainClass in lazabs.horn.bottomup.MainArrays \
                 lazabs.horn.bottomup.MainADT \
                 lazabs.horn.bottomup.MainList \
                 lazabs.horn.bottomup.MainBV \
                 lazabs.horn.bottomup.MainBV2; do
    echo
    echo $mainClass
    java $JAVA_OPTS $mainClass 2>&1 | grep -iv time | grep -v 'ms)' | sed -e 's/Map(.*$//g'
done
